# Generated by Django 5.1.2 on 2024-10-20 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_phoneNum',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
